<a href="https://colab.research.google.com/github/lol-mann/Data_analytics/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.


you can consider arrays as a matrix in mathematics.

ex: 

$
\begin{bmatrix}
1 & 2 & 3\\
a & b & c
\end{bmatrix}
$




![alt text](https://i.ibb.co/2hJYCvf/Untitled.png)

numpy arrays are fast and lightweight

In [0]:
test_list = []
for i in range(100000000):
  test_list.append(i)

CPU times: user 11.8 s, sys: 3.53 s, total: 15.4 s
Wall time: 15.4 s


In [0]:
%%time
test_list = [x**0.5 for x in test_list]

CPU times: user 18.2 s, sys: 3.15 s, total: 21.4 s
Wall time: 21.4 s


In [0]:
import numpy as np
test_array=np.array(test_list)

In [0]:
%%time
test_array=np.sqrt(test_array)

CPU times: user 205 ms, sys: 9.03 ms, total: 214 ms
Wall time: 215 ms


initializing

In [0]:
#you can initialize an array from a list
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [0]:
print(type(a))

<class 'numpy.ndarray'>


In [0]:
#you can also specify the memory it uses
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [0]:
# Get Type
print(a.dtype)

dtype('int16')

In [0]:
# Get Size of individual element in array
print(a.itemsize)

2

In [0]:
# Get total size
print(a.nbytes)
# you can also use 
print(a.itemsize*a.size)

6
6


In [0]:
#initializing a two dimentional array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [0]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


index and accessing elements

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
b=np.array([
            [[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],
            [[15,16,17,18,19,20,21],[22,23,24,25,26,27,28]],
            [[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]
            ])
print(b)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 27 28]]

 [[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]]


In [7]:
#to find the first element of fifth column
a[0,4]

5

In [9]:
#to find the second element of fifth column
a[1,4]

12

In [10]:
#to find the second element of fifth column
a[1,-3]

12

In [15]:
#to get the entire first row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#to get the entire first column
a[:,0]

array([1, 8])

In [16]:
#to get the entire third column
a[:,2]

array([ 3, 10])

In [17]:
#indexing -> [start:end(exclusive):step]
#first row 
a[0, 1:-1:2]

array([2, 4, 6])

In [20]:
#changing the values 
a[1,5] = 200
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 200  14]]


In [23]:
#changing a value of entire row
a[:,2] = 99
print(a)

[[  1   2  99   4   5   6   7]
 [  8   9  99  11  12 200  14]]


In [24]:
#changing a value of entire row
a[:,2] = [88,108]
print(a)

[[  1   2  88   4   5   6   7]
 [  8   9 108  11  12 200  14]]


In [35]:
b[:,:,-1] = [[100,100],
            [100,100],
            [100,100]]
print(b)

[[[100   2   3   4   5   6 100]
  [100   9  10  11  12  13 100]]

 [[100  16  17  18  19  20 100]
  [100  23  24  25  26  27 100]]

 [[100   2   3   4   5   6 100]
  [100   9  10  11  12  13 100]]]


Initializing Different Types of Arrays easily

In [37]:
# to create a matrix of all 0s of shape 2x3
np.zeros((2,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [38]:
# to create a matrix of all 0s of shape 2x3
np.zeros((2,3),dtype='float32')

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [39]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [41]:
#with any other number example 8 of shape 4x4
np.full((4,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

Initializing Different Types of Arrays randomly

In [42]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.20362452, 0.21790423],
       [0.87915298, 0.4358802 ],
       [0.05310168, 0.42732905],
       [0.27235479, 0.66319523]])

In [43]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 5, -4,  3],
       [ 5,  5,  7],
       [-1,  3, -3]])

In [44]:
# The identity matrix - by default it's a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics with numpy

In [52]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [53]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [54]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [55]:
print(a ** 2)

[ 1  4  9 16]


In [56]:
print(a ** a)

[  1   4  27 256]


In [58]:
# Take the sin or cos
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


Linear Algebra

In [63]:
#matrix multiplication
a = np.ones((2,3))

b = np.full((3,2), 2)
print(a , b )

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]][[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [68]:
# Find the determinant
c = np.identity(3)
print(c)
print()
print(np.linalg.det(c))
print()
print(np.matmul(a,b))
print()
print(np.linalg.det(np.matmul(a,b)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

1.0

[[6. 6.]
 [6. 6.]]

0.0


In [0]:
A,L = np.linalg.eig(np.diag((1,2,3)))

In [74]:
A

array([1., 2., 3.])

In [75]:
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

statistics

In [76]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.min(stats)

1

In [78]:
np.max(stats)

6

In [79]:
np.max(stats, axis=1)

array([3, 6])

In [80]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [81]:
np.sum(stats, axis=1)

array([ 6, 15])